services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Только HTTP entrypoint
      - "--entrypoints.web.address=:80"

      # Динамические правила, если нужны
      - "--providers.file.directory=/dynamic/"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Монтируем динамические правила
      - ./dynamic:/dynamic:ro
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true