services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # HTTP entrypoint
      - "--entrypoints.web.address=:80"

      # Dashboard entrypoint
      - "--entrypoints.traefik.address=:8080"

      # Включаем dashboard
      - "--api.dashboard=true"

      # Роутер для dashboard
      - "--api.insecure=true"

      # Динамические правила, если нужны
      - "--providers.file.directory=/dynamic/"
      - "--providers.file.watch=true"
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/dynamic:ro
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true